services:
  zenoh-router:
    image: eclipse/zenoh:latest
    networks: [rov-net]

  simulator:
    image: ghcr.io/joaoluizthomazetti/rov-telemetry-simulator:latest
    volumes: [mcap_data:/data]
    environment:
      - ZENOH_CONNECT=tcp/zenoh-router:7447
    networks: [rov-net]
    depends_on: [zenoh-router]

  recorder:
    image: ghcr.io/joaoluizthomazetti/rov-telemetry-recorder:latest
    volumes: [mcap_data:/data]
    environment:
      - MCAP_DIR=/data
      - ZENOH_CONNECT=tcp/zenoh-router:7447
    networks: [rov-net]
    depends_on: [zenoh-router]

  backend:
    image: ghcr.io/joaoluizthomazetti/rov-telemetry-backend:latest
    volumes: [mcap_data:/data]
    environment:
      - MCAP_DIR=/data
      - ZENOH_CONNECT=tcp/zenoh-router:7447
    networks: [rov-net]
    depends_on: [zenoh-router]

  frontend:
    image: ghcr.io/joaoluizthomazetti/rov-telemetry-frontend:latest
    ports: ["127.0.0.1:8888:80"]
    networks: [rov-net]
    depends_on: [backend]

networks:
  rov-net:

volumes:
  mcap_data:
